import type { z } from 'zod'

export interface ToolDefinition<T extends z.ZodObject> {
  name: string
  description: string
  strict?: boolean
  required?: boolean
  schema: T
  execute: (args: z.infer<T>) => string | Promise<string>
}

export interface ToolCall {
  type: 'function'
  function: {
    name: string
    description: string
    parameters: Record<string, any>
    strict?: boolean
  }
}

export type ToolChoice = 'auto' | 'none' | 'required' | {
  type: 'function'
  function: {
    name: string
  }
}

/**
 * The tool calls generated by the model.
 */
export interface ChatCompletionTool {
  /**
   * The ID of the tool call.
   */
  id: string
  /**
   * The type of the tool. Currently, only **function** is supported.
   */
  type: 'function'
  /**
   * The function that the model called.
   */
  function: {
    /**
     * The name of the function to call.
     */
    name: string
    /**
     * The arguments to call the function with, as generated by the model in JSON format.
     *
     * Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
     *
     * Validate the arguments in your code before calling your function.
     */
    arguments: string
  }
}
